
export const FIND_PATIENT_TESTING_RESULT_REQUEST = 'FIND_PATIENT_TESTING_RESULT_REQUEST';
export const FIND_PATIENT_TESTING_RESULT_SUCCESS = 'FIND_PATIENT_TESTING_RESULT_SUCCESS';
export const FIND_PATIENT_TESTING_RESULT_FAILURE = 'FIND_PATIENT_TESTING_RESULT_FAILURE';
