
export const CREATE_GEN_TESING_REQUEST = 'CREATE_GEN_TESING_REQUEST';
export const CREATE_GEN_TESING_SUCCESS = 'CREATE_GEN_TESING_SUCCESS';
export const CREATE_GEN_TESING_FAILURE = 'CREATE_GEN_TESING_FAILURE';
